### ISSUE TITLE
Outdated langchain-openai dependency

### ISSUE THREAD

**Issue by cv** [langwatch/langevals#3]
Hi! 👋 

I'm having trouble installing `langevals-ragas` due to this dependency being outdated:

https://github.com/langwatch/langevals/blob/eb1f6a638459b97cc4f0cb4595cc569ca2a98fcb/evaluators/ragas/pyproject.toml#L12

We have some code that relies on `langchain-openai > 0.1.0`, and from a cursory look it seems like it would be a straightforward upgrade. Would you be interested in a PR for this?

**Comment by rogeriochaves** [comment]
Of course, send it our way! If any conflicts, might be in ragas, but I see we need to also update ragas version to 0.1.7, might as well do that later today
